#!/bin/sh

./maple-util
#./reset.py

./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
./maple-util -l
